### ISSUE TITLE
This is not working with windows

### ISSUE THREAD

**Issue by skprasadu** [sqshq/PiggyMetrics#10]
First of all, your sample is great. I followed as below,

a. I installed dockertoolbox on windows, opened the "Docker Quickstart Terminal: and went to git cloned location and run mvn clean install
b. eval "$(docker-machine env default)"
c. docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

I am getting below error, 

ERROR: for auth-mongodb  Container command '/init.sh' not found or does not exist.

ERROR: for notification-mongodb  Container command '/init.sh' not found or does not exist.

ERROR: for statistics-mongodb  Container command '/init.sh' not found or does not exist.

ERROR: for account-mongodb  Container command '/init.sh' not found or does not exist.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1

Can you tell me what is going on?

**Comment by sqshq** [comment]
I have no windows machine to check it out, but your error message looks like a bug in docker compose:

> File "compose\cli\main.py", line 63, in main
> AttributeError: 'ProjectError' object has no attribute 'msg'

https://github.com/docker/compose/issues/3519

**Comment by sqshq** [comment]
Anyway, try to start containers in a production mode (directly from Docker Hub)

**Comment by Braidner** [comment]
Try to use [docker beta client](https://beta.docker.com/) for windows.
