### ISSUE TITLE
How to build and Run without docker?

### ISSUE THREAD

**Issue by ahashmi929** [sqshq/PiggyMetrics#11]
I've tried to build using mvn and tried to run. config runs perfect but  when i run any other microservice it ```
shows  Error:
"org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config:8888/auth-service/default": config; nested exception is java.net.UnknownHostException: config
```"

How to fix it?

**Comment by sqshq** [comment]
`config` is an alias in a docker network
Without docker, you should provide an IP address, where your service runs.

`localhost` will work, if you run locally

**Comment by ahashmi929** [comment]
changed all alias in host and url. What about the config export passwords? how to set it on windows? because microservice could not locate propertySource and Unauthorized http connect.

**Comment by sqshq** [comment]
You can get all the information from README and docker-compose files.

**Comment by fattyhan** [comment]
should i add the service name when i connect the config server？
