### ISSUE TITLE
The repository not work

### ISSUE THREAD

**Issue by fattyhan** [sqshq/PiggyMetrics#14]
Configuration doesn't change, i have to start all applications and the mongo is connected,but the repository didn't work,i  can't do anything about CRUD actions.There is no exception is thrown just got null when i ran the find method,It looks too quiet! Can you help me?who knows why.. ...

**Comment by Sridharc20** [comment]
I've cloned your code and tried to ran the application on my local machine using Docker. However, it seems the gateway portal is unable to establish the connection with the registry service that's what the logs says. Can you please shed some lights.

**Comment by fattyhan** [comment]
Tks Sridharc20,,you should clone it from a new address. [PiggyCopy](https://github.com/fattyhan/piggyCopy),please~
