### ISSUE TITLE
Auth-service - OAuth 2.0/Password Grant issue

### ISSUE THREAD

**Issue by luchob** [sqshq/PiggyMetrics#16]
Sasha, I've been wondering about this configuration:

	clients.inMemory()
		.withClient("browser")
		.authorizedGrantTypes("refresh_token", "password")
		.scopes("ui")

If I run the auth service in isolation any access to `/ouath/token` with this client id (no client secret for basic auth header) ends with 401 unless I enable the so called authentication for client:

        public void configure(AuthorizationServerSecurityConfigurer oauthServer)
			throws Exception {
		oauthServer.
                        ...
			allowFormAuthenticationForClients();
	} 

Then it works because this adds the `ClientCredentialsTokenEndpointFilter` to the filter chain **before** the basic auth filter kicks in. Otherwise I would be authenticated as anonymous and I'll never reach the endpoint. Then I have to permit the check token access for anyone, so that this client is able to check its token at this endpoint - `/oauth/check_token`.  This is done in the following way - `checkTokenAccess("permitAll()")`. What I see is that you have secured the endpoint for authenticated users though...

Is this a bug or I can't see something obvious? 

I'm testing on 1.5.3, see also similar config [here](https://github.com/luchob/oauth2-passwordgrant-example/blob/demo1/auth/src/main/java/eu/balev/demo/auth/config/OAuth2Config.java#L63-L69).

**Comment by luchob** [comment]
Hi again, I've seen how you use this config and things got clarified even after short discussion with spring-security dev [here ](https://github.com/spring-projects/spring-security-oauth/issues/1058) :-)

**Comment by sqshq** [comment]
👍  Yes, Dave is awesome :)
