### ISSUE TITLE
FRONTEND: migrate and refactor the whole javascript/jquery codebase to a modern frontend framework

### ISSUE THREAD

**Issue by sqshq** [sqshq/PiggyMetrics#27]
Nice to have: 
Migrate and refactor the whole javascript/jquery codebase to a modern frontend framework (no preference from my side). This task has nothing to do with Microservices, but I feel it is a right thing to do since this project became pretty popular)

**Comment by ctooley21** [comment]
Just found this project on issuehub.io. It's a very interesting application. I have some experience with Angular 6. Would you be interested in converting to that?
