### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by scharanjit** [sqshq/PiggyMetrics#3]
I'm getting below error while running docker-compose up -d

===========================================================================
_ERROR: for registry  driver failed programming external connectivity on endpoint fc6c4f02045f_fc6c4f02045f_fc6c4f02045f_piggymetricsmaster_registry_1 (fca3878553c3451a035a37346384f70c459e08837e6baf8eac1ded6ba5ba9da2): Bind for 0.0.0.0:8761 failed: port is already allocated

ERROR: for gateway  driver failed programming external connectivity on endpoint d83d93d0e448_d83d93d0e448_d83d93d0e448_piggymetricsmaster_gateway_1 (f4301c67a79ed0748b77bf257870a88486d5973fcc73aa06a07dfd2b888489ce): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'_

=============================================================================

**Comment by scharanjit** [comment]
I checked  port 8761...nothing is running on it
```
netstat -tlnp | grep "8761"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::8761                 :::*                    LISTEN      -  
```

**Comment by scharanjit** [comment]
> Neither on 80

```

netstat -tlnp | grep "80"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::8000                 :::*                    LISTEN      -               
tcp6       0      0 :::28000                :::*                    LISTEN      -    
```

**Comment by sqshq** [comment]
Never faced the problem. Looks like it has nothing in common with the PiggyMetrics itself.
See fresh discussions in Docker issues: https://github.com/docker/docker/issues/8714
