### ISSUE TITLE
Not able to build the config server project

### ISSUE THREAD

**Issue by Jcprout** [sqshq/PiggyMetrics#5]
I'm having problems building the config project; this is the error:

[ERROR] Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-netflix-dependencies:pom:1.1.2.RELEASE in spring-snapshots (https://repo.spring.io/snapshot) @ org.springframework.cloud:spring-cloud-sleuth-dependencies:1.0.2.BUILD-SNAPSHOT, /Users/jprout/.m2/repository/org/springframework/cloud/spring-cloud-sleuth-dependencies/1.0.2.BUILD-SNAPSHOT/spring-cloud-sleuth-dependencies-1.0.2.BUILD-SNAPSHOT.pom, line 22, column 16
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-config-server:jar is missing. @ line 27, column 15

I've tried changing the version of spring-boot-starter-parent to 1.3.5-RELEASE but this didn't help.

Any ideas?

**Comment by sqshq** [comment]
I've just merged a pool request with some dependencies updates. 
Travis CI build passed successfully: https://travis-ci.org/sqshq/PiggyMetrics/builds/138173296

Try to clean your local .m2 directory if it still doesn't work for you

**Comment by Jcprout** [comment]
Yes, it's building after picking up the new dependencies - Thanks!
