### ISSUE TITLE
Monitoring Docker containers

### ISSUE THREAD

**Issue by lduparc** [sqshq/PiggyMetrics#6]
Hi @sqshq,

Thank you for your explanations and this full sample project using Docker.

How have we the ability to monitor docker containers (cpu, memory, health, others metrics) in order to be alerted if an instance is UP or Down ...etc ? What kind of tools exist to help us in a production environnement to identify problems, scale containers, manage memory ?

Regards,

**Comment by sqshq** [comment]
Hi,
Containers orchestration, monitoring and scale is a huge topic. You can start with an [overview article about Swarm, Mesos and Kubernetes.](https://www.oreilly.com/ideas/swarm-v-fleet-v-kubernetes-v-mesos)
