### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by lduparc** [sqshq/PiggyMetrics#8]
Hi,

I try to login after created an account but it doesn't work.
An alert appear to notify "Somethings went wrong" but I can't see any error on logs.

see errors on Chrome : 

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

> POST http://localhost/uaa/oauth/token 401 (Unauthorized)
> send @ jquery.min.js:2
> ajax @ jquery.min.js:2
> requestOauthToken @ launch.js:16
> success @ login.js:29
> k @ jquery.min.js:2
> fireWith @ jquery.min.js:2
> y @ jquery.min.js:2
> d @ jquery.min.js:2

> main.js:7 Uncaught TypeError: Cannot read property 'name' of null
> initAccount @ main.js:7
> success @ login.js:30
> k @ jquery.min.js:2
> fireWith @ jquery.min.js:2
> y @ jquery.min.js:2
> d @ jquery.min.js:2

**Comment by sqshq** [comment]
401 error means your login and password don't match (or don't exist). Make sure that all account creation proccess was successful and there is a record in db.

There are plenty of logs in several services after any request. Please, provide them all if you still have an issue.

**Comment by Braidner** [comment]
In new version of spring cloud zuul removes custom headers for requets to services, default headers are "Cookie,Set-Cookie,Authorization",  that means when your zuul send request to uaa he drops Authorization. Fix: add to zuul config empty sensitiveHeaders param: 
`  
routes:
 auth-service:
        path: /uaa/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders: 
`

**Comment by sqshq** [comment]
Fixed this.
@Braidner, thank you for the help.
@lduparc, it works again, you can check it out.
