### ISSUE TITLE
Run with "Connection refused" error and 401 error 

### ISSUE THREAD

**Issue by lvguanming** [sqshq/PiggyMetrics#9]
hi,
I am already export `env vars` use command like this  where run docker-compose:

> export CONFIG_SERVICE_PASSWORD=1111 (other 4 variables also export)

but , when execute 'docker-compose ...' ,throw connection refused error.(all auth's client throw this error )

Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config:8888/registry/default": Connection refused; nested exception is java.net.ConnectException: Connection refused

I use command `ping` config host it's ok...

where i checked it ? thanks....

**Comment by sqshq** [comment]
It's hard to guess without logs from config service and the service you are requested it from.
But it looks like config service is just still starting when you noticed this errors.

See https://github.com/sqshq/PiggyMetrics#notes-2
